config/routes.rb
Rails.application.routes.draw do
  root 'search#index'
  get 'search/query', as: :search_query
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
   def index
     form Search::Create
   end

   def create
     run Search::Create

     render action: :index
   end

  def process; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataSearchable</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/search/_form.html.erb
<div class="col-md-12">
  <%= form_tag search_query_path, method: :get, id: 'search_form', class: 'input-group', 'data-url': search_query_path(format: :json) do |f| %>
      <%= text_field_tag :query, params[:query], required: true, placeholder: "Search", id: "query", class: "form-control" %>
      <%= button_tag "Search", name: nil, class: "input-group-append btn btn-primary" %>
  <% end %>
</div>

app/views/search/query.html.erb
<div class="row mt-4 mb-4 ml-3">
  <h2>Search Lang Data</h2>
</div>

<%= render 'form' %>

<div class="row mt-4">
  <ul>
    <% @results.each do |row| %>
      <li>
        <p><b>Lang Name:</b> <%= row['Name'] %></p>
      </li>
      <li>
        <p><b>Type:</b> <%= row['Type'] %></p>
      </li>
      <li>
        <p><b>Designed by:</b> <%= row['Designed by'] %></p>
      </li>
      <p>--------------------------------------------------------------------------------------------------</p>
    <% end %>
  </ul>
</div>